swagger: "2.0"
info:
  title: blog
  description: mobile has every tool to get any job done, so codename for the new
    mobile APIs.
  version: 1.0.0
  contact:
    email: astaxie@gmail.com
paths: {}
definitions:
  .Customer:
    type: object
